.ORG 0x0000
				JMP		RESET				; RESET VECTOR
.ORG OC0Baddr
				JMP		TIM0_CPA				; TIMER MATCH REG B VECTOR

RESET:
				LDI		R16, HIGH(RAMEND)		; INITALISE STACK POINTER
				OUT		SPH, R16
				LDI		R16, LOW(RAMEND)
				OUT		SPL, R16

				SBI		DDRB, 0X05			; SET PORTB0 FOR OUTPUT

				LDI		R16, 0X09			; SET PRESCALER TO NO PRESCALING AND COMPARE MODE
				OUT		TCCR0B, R16			; TIMER/COUNTER CONTROL REGISTER "B"

				LDI		R16, 0X3F			; SET COMPARE VALUE (APPROX 4.7US INTERRUPT)
				OUT		OCR0B, R16

				LDI		R16, 0x04			; SET TIMER INTERRUPT MASK TO COMPARE MODE
				STS		TIMSK0, R16			

				LDI		R16, 0X00			; INITIALISE COUNTER TO 0
				OUT		TCNT0, R16
				SEI						; ENABLE INTERUPTS GLOBALLY
				JMP		MAIN_LOOP			; START MAIN LOOP

MAIN_LOOP:
				NOP						; DO NOTHING
				JMP		MAIN_LOOP

TIM0_CPA:
				SBI		PINB, 5				; FLIP THE 0 BIT
				LDI		R16, 0X00			; RESET COUNTER TO 0
				OUT		TCNT0, R16
				RETI
